# pubspec.yaml
name: habit_tracker_fixed
description: A habit tracking app for two people

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.1.0
  intl: ^0.18.1
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/9B61E793-016F-4BD3-BD32-EDBFEC1D3A9D.jpg

